packages:
  - packages/*
  - packages/playground/**
catalog:
  "@antfu/eslint-config": ^2.13.0
  "@clack/prompts": ^0.7.0
  "@commitlint/cli": ^17.8.1
  "@commitlint/config-conventional": ^17.8.1
  "@eslint-react/eslint-plugin": ^1.5.8
  "@stylistic/eslint-plugin-migrate": ^1.7.0
  "@types/cross-spawn": ^6.0.6
  "@types/eslint": ^8.56.5
  "@types/fs-extra": ^11.0.4
  "@types/hash-sum": 1.0.2
  "@types/minimist": ^1.2.5
  "@types/prompts": ^2.4.9
  "@types/react": ^18.3.1
  "@types/yargs": ^17.0.32
  "@unocss/eslint-plugin": ^0.59.0
  "@vue/component-compiler": ^4.2.3
  "@vue/component-compiler-utils": ^3.3.0
  bumpp: ^9.4.0
  citty: ^0.1.6
  cross-spawn: ^7.0.3
  defu: ^6.1.4
  esbuild-sass-plugin: ^3.2.0
  eslint-flat-config-viewer: ^0.1.11
  eslint-plugin-format: ^0.1.0
  eslint-plugin-react: ^7.34.0
  eslint-plugin-react-hooks: ^4.6.0
  eslint-plugin-react-refresh: ^0.4.6
  esno: ^4.7.0
  execa: ^8.0.1
  fast-glob: ^3.3.2
  fs-extra: ^11.2.0
  gradient-string: ^2.0.2
  hash-sum: ^2.0.0
  kolorist: ^1.8.0
  lint-staged: ^15.2.2
  magic-string: ^0.30.8
  minimist: ^1.2.8
  parse-gitignore: ^2.0.0
  picocolors: ^1.0.0
  postcss-less: ^6.0.0
  postcss-scss: ^4.0.9
  prettier-eslint: 16.3.0
  prompts: ^2.4.2
  rimraf: ^5.0.5
  stylelint: ^16.2.1
  stylelint-config-css-modules: ^4.4.0
  stylelint-config-standard: ^36.0.0
  stylelint-declaration-block-no-ignored-properties: ^2.8.0
  stylelint-prettier: ^5.0.0
  tsup: ^8.0.2
  tsx: ^4.7.1
  turbo: ^1.13.0
  unconfig: ^0.3.12
  vitepress: ^1.1.0
  vitepress-plugin-search: ^1.0.4-alpha.22
  vue-template-compiler: 2.6.11
  yargs: ^17.7.2
