stages:
  - deploy

variables:
  PNPM_VERSION: 8

cache:
  paths:
    - ~/.pnpm-store

before_script:
  - curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@$PNPM_VERSION
  - npm config set @klook:registry=https://knpm.klook.io/ --location project
  - npm config set //knpm.klook.io/:_authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWFsX2dyb3VwcyI6WyJrbG9va3VzZXIxIl0sIm5hbWUiOiJrbG9va3VzZXIxIiwiZ3JvdXBzIjpbImtsb29rdXNlcjEiLCIkYWxsIiwiJGF1dGhlbnRpY2F0ZWQiLCJAYWxsIiwiQGF1dGhlbnRpY2F0ZWQiLCJhbGwiLCJrbG9va3VzZXIxIl0sImlhdCI6MTYwMzI2MTU5NCwibmJmIjoxNjAzMjYxNTk0LCJleHAiOjQ3NTkwMjE1OTR9.ozCIv4PITRUE4V34nuTEu-ZJBzckbEvvNQABt-l1mlk --location project

# |-----------------------------------------------------------------
# | 开启 AI code review 功能, 如需关闭此功能，可以将下面代码注释掉
# |-----------------------------------------------------------------
include:
  - project: 'ops-public/ci-templates'
    file: 'build/multiple/node/web-base.yml'

cr-robot:
  extends: .cr-robot
# |-----------------------------------------------------------------

# 开启 gitlab 静态站点部署
pages:
  image: registry.klook.io/node/node:16
  stage: deploy
  only:
    - master
  tags:
    - docker
  script:
    - pnpm install -no-frozen-lockfile
    - rm -rf public
    - pnpm run docs:build
  allow_failure: true
  artifacts:
    paths:
      # 部署产物路径 root/public
      - public
